Skip to main content
Codingo
HOME
WRITEUPS
GITHUB ACCOUNT
LINKEDIN
CONTACT

Solving the SC1:Math Bot Capture the Flag Challenge with Python

 February 14, 2017  Michael Skelton  Capture the flag, Security, Tutorial
 Summary
 The MSP Tech Club puts on an annual CTF, available here. After stumbling upon the channel on IRC (#alexctf on Freenode) I felt compelled to compete in order to test the lessons that I’ve been learning throughout my OSCP course, the summary of which is below.


         The MSP:Math Bot CTF Challenge Explained
         The challenge presents two mirrored servers to connect to using netcat. Connecting to either presents a prompt not unlike the following:



         Answering each question manually re-presents a new mathematical problem which suggests that the answer to the challenge is to write a bot which can answer the questions to proceed to the next step.

         CTF Challenge Solution and flag
         After writing a script to connect to the server and handle the equation I realised that a number of results were returned with a variety of operators. Further tweaking to the script allowed it to continually answer mathematical questions presented to it allowed it to answer 500 questions and reveal the flag:



         Resulting Python Script
         The final script is preserved below:


#!/usr/bin/python3
 
import socket
import re
import operator

MAXBUF = 4096
SENTINEL = 'ALEXCTF'
CTF_BOT = ('195.154.53.62', 1337)
OPERATIONS = {
        '+': operator.add,
            '-': operator.sub,
                '*': operator.mul,
                    '/': operator.floordiv,  # // operator
                        '%': operator.mod
                        }

if __name__ == '__main__':
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client.connect(CTF_BOT)
         
            while True:
                    data = b''

                            # receive and store data
                                    while True:
                                                chunk = client.recv(MAXBUF)
                                                            data += chunk
                                                                        if len(chunk) < MAXBUF:
                                                                                        break
                                                                                                
                                                                                                # store decoded data for future usage
         decoded = data.decode('utf-8')

                 # our flag contains ALEXCTF, once it's revealed print recevied data and exit
                         if SENTINEL in decoded:
                                         print(decoded)
                                                     break
                                                         
                                                         # \d+ matches a digit (equal to [0-9])
                                                                 # .{3} matches any  character, except line terminators exactly three times
                                                                         match = re.search('\d+.{3}\d+', decoded)
                                                                                 if not match:
                                                                                                 raise ValueError("Invalid expression string")
                                                                                                     
                                                                                                     expression = match.group(0)
                                                                                                      
                                                                                                              # properly handle division
                                                                                                                      if '/' in expression:
                                                                                                                                      expression = expression.replace('/', '//')
                                                                                                                                       
                                                                                                                                               result = eval(expression)
                                                                                                                                                
                                                                                                                                                        # print results to screen to see script progress
                                                                                                                                                                print(expression + ' = ' + str(result))

                                                                                                                                                                        # encode and transfer
                                                                                                                                                                                data = str(result).encode('utf-8') + b'\n'
                                                                                                                                                                                        client.send(data)
                                                                                                                                                                                        1
                                                                                                                                                                                        2
                                                                                                                                                                                        3
                                                                                                                                                                                        4
                                                                                                                                                                                        5
                                                                                                                                                                                        6
                                                                                                                                                                                        7
                                                                                                                                                                                        8
                                                                                                                                                                                        9
                                                                                                                                                                                        10
                                                                                                                                                                                        11
                                                                                                                                                                                        12
                                                                                                                                                                                        13
                                                                                                                                                                                        14
                                                                                                                                                                                        15
                                                                                                                                                                                        16
                                                                                                                                                                                        17
                                                                                                                                                                                        18
                                                                                                                                                                                        19
                                                                                                                                                                                        20
                                                                                                                                                                                        21
                                                                                                                                                                                        22
                                                                                                                                                                                        23
                                                                                                                                                                                        24
                                                                                                                                                                                        25
                                                                                                                                                                                        26
                                                                                                                                                                                        27
                                                                                                                                                                                        28
                                                                                                                                                                                        29
                                                                                                                                                                                        30
                                                                                                                                                                                        31
                                                                                                                                                                                        32
                                                                                                                                                                                        33
                                                                                                                                                                                        34
                                                                                                                                                                                        35
                                                                                                                                                                                        36
                                                                                                                                                                                        37
                                                                                                                                                                                        38
                                                                                                                                                                                        39
                                                                                                                                                                                        40
                                                                                                                                                                                        41
                                                                                                                                                                                        42
                                                                                                                                                                                        43
                                                                                                                                                                                        44
                                                                                                                                                                                        45
                                                                                                                                                                                        46
                                                                                                                                                                                        47
                                                                                                                                                                                        48
                                                                                                                                                                                        49
                                                                                                                                                                                        50
                                                                                                                                                                                        51
                                                                                                                                                                                        52
                                                                                                                                                                                        53
                                                                                                                                                                                        54
                                                                                                                                                                                        55
                                                                                                                                                                                        56
                                                                                                                                                                                        57
                                                                                                                                                                                        58
                                                                                                                                                                                        59
#!/usr/bin/python3
                                                                                                                                                                                         
                                                                                                                                                                                         import socket
                                                                                                                                                                                         import re
                                                                                                                                                                                         import operator
                                                                                                                                                                                          
                                                                                                                                                                                          MAXBUF = 4096
                                                                                                                                                                                          SENTINEL = 'ALEXCTF'
                                                                                                                                                                                          CTF_BOT = ('195.154.53.62', 1337)
                                                                                                                                                                                          OPERATIONS = {
                                                                                                                                                                                                      '+': operator.add,
                                                                                                                                                                                                          '-': operator.sub,
                                                                                                                                                                                                              '*': operator.mul,
                                                                                                                                                                                                                  '/': operator.floordiv,  # // operator
                                                                                                                                                                                                                      '%': operator.mod
                                                                                                                                                                                                                      }
                                                                                                                                                                                           
                                                                                                                                                                                          if __name__ == '__main__':
                                                                                                                                                                                                  client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                                                                                                                                                                                                      client.connect(CTF_BOT)
                                                                                                                                                                                                       
                                                                                                                                                                                                           while True:
                                                                                                                                                                                                                       data = b''
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                # receive and store data
                                                                                                                                                                                                                                        while True:
                                                                                                                                                                                                                                                        chunk = client.recv(MAXBUF)
                                                                                                                                                                                                                                                                    data += chunk
                                                                                                                                                                                                                                                                                if len(chunk) < MAXBUF:
                                                                                                                                                                                                                                                                                                    break
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                        # store decoded data for future usage
                                                                                                                                                                                                                                                                                                                decoded = data.decode('utf-8')
                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                         # our flag contains ALEXCTF, once it's revealed print recevied data and exit
                                                                                                                                                                                                                                                                                                                                 if SENTINEL in decoded:
                                                                                                                                                                                                                                                                                                                                                 print(decoded)
                                                                                                                                                                                                                                                                                                                                                             break
                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                 # \d+ matches a digit (equal to [0-9])
                                                                                                                                                                                                                                                                                                                                                                         # .{3} matches any  character, except line terminators exactly three times
                                                                                                                                                                                                                                                                                                                                                                                 match = re.search('\d+.{3}\d+', decoded)
                                                                                                                                                                                                                                                                                                                                                                                         if not match:
                                                                                                                                                                                                                                                                                                                                                                                                         raise ValueError("Invalid expression string")
                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                             expression = match.group(0)
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                      # properly handle division
                                                                                                                                                                                                                                                                                                                                                                                                                              if '/' in expression:
                                                                                                                                                                                                                                                                                                                                                                                                                                              expression = expression.replace('/', '//')
                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                       result = eval(expression)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                # print results to screen to see script progress
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(expression + ' = ' + str(result))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 # encode and transfer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         data =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         str(result).encode('utf-8')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         + b'\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 client.send(data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Capture the flag
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Penetration testing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Post navigation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  WordPress Security
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Basics
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  CTF Writeup –
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  CrikeyCon 2017:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Fast Math 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      RECENT POSTS

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      CTF Writeup –
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      CrikeyCon
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2017:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Impossible
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Math
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          CTF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Writeup –
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          CrikeyCon
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2017: Fast
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Math
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Solving
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          the
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          SC1:Math
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Capture
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          the Flag
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Challenge
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          with
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Python
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          WordPress
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Security
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Basics
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          A concise
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          guide to
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          effectively
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          designing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          donation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pages
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          CATEGORIES

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Australia
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Best
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Practice
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Bitcoin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Capture
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          the flag
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Change
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Coin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Manual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          (General)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Cryptography
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          (General)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Digital
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Marketing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Dogecoin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Enterprise
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Content
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Forms
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Information
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Investing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Litecoin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Problems
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          and
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Solutions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Regulation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Security
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sharepoint
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          SharePoint
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Administration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          SharePoint
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Development
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          SQL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Tax
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Tutorial
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Uncategorized
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Vendors
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Visual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Studio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          WordPress
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          RSS RECENT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          SECURITY
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          BREACHES

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Abandonia
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          - 776,125
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            breached
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            accounts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Edmodo -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            43,423,561
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            breached
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            accounts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            DaFont -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            637,340
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            breached
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            accounts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            HOME
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             WRITEUPS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              GITHUB
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ACCOUNT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               LINKEDIN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CONTACT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sparkling
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Theme
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                by
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Colorlib
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Powered
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                by
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WordPress
